package ec.edu.ups.pw59.clienteAutoEv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2022-02-01T12:31:06.197-05:00
 * Generated source version: 3.4.4
 *
 */
@WebService(targetNamespace = "http://beans.evaWiliamChablaSRV.pw59.ups.edu.ec/", name = "ContactosServiceSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface ContactosServiceSOAP {

    @WebMethod
    @RequestWrapper(localName = "getContactos", targetNamespace = "http://beans.evaWiliamChablaSRV.pw59.ups.edu.ec/", className = "ec.edu.ups.pw59.clienteAutoEv.GetContactos")
    @ResponseWrapper(localName = "getContactosResponse", targetNamespace = "http://beans.evaWiliamChablaSRV.pw59.ups.edu.ec/", className = "ec.edu.ups.pw59.clienteAutoEv.GetContactosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ec.edu.ups.pw59.clienteAutoEv.Vehiculo> getContactos()
;

    @WebMethod
    @RequestWrapper(localName = "crearContacto", targetNamespace = "http://beans.evaWiliamChablaSRV.pw59.ups.edu.ec/", className = "ec.edu.ups.pw59.clienteAutoEv.CrearContacto")
    @ResponseWrapper(localName = "crearContactoResponse", targetNamespace = "http://beans.evaWiliamChablaSRV.pw59.ups.edu.ec/", className = "ec.edu.ups.pw59.clienteAutoEv.CrearContactoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String crearContacto(

        @WebParam(name = "arg0", targetNamespace = "")
        ec.edu.ups.pw59.clienteAutoEv.Vehiculo arg0
    );
}
