package ec.edu.ups.pw59.clienteAutoEv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2022-02-01T12:31:06.208-05:00
 * Generated source version: 3.4.4
 *
 */
@WebServiceClient(name = "ContactosServiceSOAPService",
                  wsdlLocation = "http://localhost:8080/evaWiliamChablaSRV/ContactosServiceSOAP?wsdl",
                  targetNamespace = "http://beans.evaWiliamChablaSRV.pw59.ups.edu.ec/")
public class ContactosServiceSOAPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://beans.evaWiliamChablaSRV.pw59.ups.edu.ec/", "ContactosServiceSOAPService");
    public final static QName ContactosServiceSOAPPort = new QName("http://beans.evaWiliamChablaSRV.pw59.ups.edu.ec/", "ContactosServiceSOAPPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/evaWiliamChablaSRV/ContactosServiceSOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ContactosServiceSOAPService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/evaWiliamChablaSRV/ContactosServiceSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ContactosServiceSOAPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ContactosServiceSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContactosServiceSOAPService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ContactosServiceSOAPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ContactosServiceSOAPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ContactosServiceSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ContactosServiceSOAP
     */
    @WebEndpoint(name = "ContactosServiceSOAPPort")
    public ContactosServiceSOAP getContactosServiceSOAPPort() {
        return super.getPort(ContactosServiceSOAPPort, ContactosServiceSOAP.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContactosServiceSOAP
     */
    @WebEndpoint(name = "ContactosServiceSOAPPort")
    public ContactosServiceSOAP getContactosServiceSOAPPort(WebServiceFeature... features) {
        return super.getPort(ContactosServiceSOAPPort, ContactosServiceSOAP.class, features);
    }

}
