
package ec.edu.ups.pw59.clienteAutoEv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by Apache CXF 3.4.4
 * 2022-02-01T12:31:06.105-05:00
 * Generated source version: 3.4.4
 *
 */
public final class ContactosServiceSOAP_ContactosServiceSOAPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://beans.evaWiliamChablaSRV.pw59.ups.edu.ec/", "ContactosServiceSOAPService");

    private ContactosServiceSOAP_ContactosServiceSOAPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ContactosServiceSOAPService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ContactosServiceSOAPService ss = new ContactosServiceSOAPService(wsdlURL, SERVICE_NAME);
        ContactosServiceSOAP port = ss.getContactosServiceSOAPPort();

        {
        System.out.println("Invoking getContactos...");
        java.util.List<ec.edu.ups.pw59.clienteAutoEv.Vehiculo> contactos = port.getContactos();
        System.out.println("getContactos.result=" + contactos);


        }
        {
        System.out.println("Invoking crearContacto...");
        ec.edu.ups.pw59.clienteAutoEv.Vehiculo contacto = null;
        
        contacto = new Vehiculo();
        contacto.setPlaca("PBC123");
        contacto.setNombre("Corvette");
        contacto.setModelo("Chebrolet");
        contacto.setColor("Blanco");
        
        java.lang.String _crearContacto__return = port.crearContacto(contacto);
        System.out.println("crearContacto.result=" + contacto);


        }

        System.exit(0);
    }

}
